debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=kafka:9092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.database.hostname=host.docker.internal
debezium.source.database.port=3306
debezium.source.database.user=root
debezium.source.database.password=12345678
debezium.source.database.connectionTimeZone=UTC
debezium.source.database.server.id=5401
debezium.source.database.server.name=sharding-mysql
debezium.source.topic.prefix=sharding
debezium.source.database.include.list=demo_sharding_0,demo_sharding_1
debezium.source.table.include.list=demo_sharding_0.t_order_0,demo_sharding_0.t_order_1,demo_sharding_1.t_order_0,demo_sharding_1.t_order_1
debezium.source.decimal.handling.mode=double
debezium.source.include.schema.changes=false

debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schemahistory.dat
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=10000

debezium.transforms=unwrap,route
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.drop.tombstones=true
debezium.transforms.unwrap.delete.handling.mode=drop
debezium.transforms.route.type=org.apache.kafka.connect.transforms.RegexRouter
debezium.transforms.route.regex=sharding\\.demo_sharding_[01]\\.t_order_[01]
debezium.transforms.route.replacement=order
